# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 15 Dec 2023 23:15:14 +0000
*               @ALL          1
*               @user         8
