<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Fri, 15 Dec 2023 23:15:14 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
