# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 15 Dec 2023 23:15:14 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

caeruy:$2y$10$q4MSEegX7bjaCWTg77DYButMOqa4RP43TDUAyYBvOFZGhs1Hh9PKG:Carlos Elcura:caeruy@gmail.com:admin,user
